### ISSUE TITLE
Small bugs running TRIP as a R-script based tool

### ISSUE THREAD

**Issue by JordanDekker** [BiodataAnalysisGroup/TRIP#1]
Hi,
First of all, nicely developed tool. Though I have encountered a few minor bugs.

When running the make_option.R script (default parameters) I got the following error message:
> Error in run_TRIP(datapath = opt$datapath, filelist = filelist, cell = opt$cell,  : 
  formal argument "aminoacid" matched by multiple actual arguments

Which is caused by the duplicate line `aminoacid = opt$aminoacid,` at line 325 in make_options.R.

Also I get the following error message when running multiple large files (on Linux):
> Error: $ operator is invalid for atomic vectors
In addition: Warning messages:
1: In run_TRIP(datapath = opt$datapath, filelist = filelist, cell = opt$cell,  :
  NAs introduced by coercion
2: In run_TRIP(datapath = opt$datapath, filelist = filelist, cell = opt$cell,  :
  NAs introduced by coercion
3: In mclapply(1:length(name), one_run, mc.cores = detectCores(all.tests = FALSE,  :
  scheduled cores 1, 2 did not deliver results, all values of the jobs will be affected
4: In mclapply(1:length(name), one_run, mc.cores = detectCores(all.tests = FALSE,  :
  scheduled core 3 encountered error in user code, all values of the job will be affected

Not sure if the detectCores function is a problem with my system (runs smooth on a Windows system). When I remove the detectCores function the program runs as  expected.

Thanks in advance.

**Comment by iofeidis** [comment]
Hello @JordanDekker,

Firstly, thank you for using our tool and providing feedback.

Regarding your first comment about the duplicate line, it has been corrected.

As for your second comment, the error was not produced by the detectCores() function. Indeed, detectCores() runs only on Linux systems, but this warning only appeared due to the data input to this function. The culprit for this error was an inner combination (merging) of data structures, which is fixed as of the latest commit.

Thanks again for your feedback and if you encounter any more bugs let us know!

**Comment by iofeidis** [comment]
Hello @JordanDekker,

Firstly, thank you for using our tool and providing feedback.

Regarding your first comment about the duplicate line, it has been corrected.

As for your second comment, the error was not produced by the detectCores() function. Indeed, detectCores() runs only on Linux systems, but this warning only appeared due to the data input to this function. The culprit for this error was an inner combination (merging) of data structures, which is fixed as of the latest commit.

Please do use TRIP for your analysis and provide feedback, so this issue can be closed.
